name: first

on : push

jobs:
  
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: date

  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: step1
        run: date

  job3:
    name: job3
    runs-on: macos-latest
    steps:
      - name: step1
        run: date

  job4:
    name: job4
    runs-on: ubuntu-latest
    needs : [job1, job2, job3]
    steps:
      - name: combined_steps
        run: date


