name: artefacts

on : push

env : 
  ARTIFACT_NAME : myartificat

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME}}
          path: .






